spring:
  application:
    name: user-service-chaika-inno

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${DB_USERNAME:chaika}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

  logging:
    level:
      root: INFO
      liquibase: INFO
      org.springframework.boot.autoconfigure.liquibase: INFO

  eureka:
    client:
      enabled: false

server:
  port: 8081